In [51]:
import re
import pandas as pd
import os
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import Word
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix
from numpy.core.umath_tests import inner1d
import nltk
from sklearn.svm import SVC  
from sklearn.metrics import classification_report, confusion_matrix

In [26]:
#data_folder = "/media/soumya/New Volume/Projects/Document Classifier/dataset"
data_folder = "../dataset"
folders = ["business","entertainment","politics","sport","tech"]

In [28]:
os.chdir(data_folder)

x = []
y = []

for i in folders:
    files = os.listdir(i)
    for text_file in files:
        file_path = i + "/" +text_file
        print("reading file:", file_path)
        with open(file_path) as f:
            data = f.readlines()
        data = ' '.join(data)
        x.append(data)
        y.append(i)

reading file: business/001.txt
reading file: business/002.txt
reading file: business/003.txt
reading file: business/004.txt
reading file: business/005.txt
reading file: business/006.txt
reading file: business/007.txt
reading file: business/008.txt
reading file: business/009.txt
reading file: business/010.txt
reading file: business/011.txt
reading file: business/012.txt
reading file: business/013.txt
reading file: business/014.txt
reading file: business/015.txt
reading file: business/016.txt
reading file: business/017.txt
reading file: business/018.txt
reading file: business/019.txt
reading file: business/020.txt
reading file: business/022.txt
reading file: business/023.txt
reading file: business/024.txt
reading file: business/025.txt
reading file: business/026.txt
reading file: business/027.txt
reading file: business/028.txt
reading file: business/029.txt
reading file: business/030.txt
reading file: business/031.txt
reading file: business/032.txt
reading file: business/033.txt
reading 

reading file: entertainment/034.txt
reading file: entertainment/035.txt
reading file: entertainment/036.txt
reading file: entertainment/037.txt
reading file: entertainment/038.txt
reading file: entertainment/039.txt
reading file: entertainment/040.txt
reading file: entertainment/041.txt
reading file: entertainment/043.txt
reading file: entertainment/044.txt
reading file: entertainment/045.txt
reading file: entertainment/046.txt
reading file: entertainment/047.txt
reading file: entertainment/048.txt
reading file: entertainment/049.txt
reading file: entertainment/050.txt
reading file: entertainment/051.txt
reading file: entertainment/052.txt
reading file: entertainment/053.txt
reading file: entertainment/054.txt
reading file: entertainment/055.txt
reading file: entertainment/056.txt
reading file: entertainment/057.txt
reading file: entertainment/058.txt
reading file: entertainment/059.txt
reading file: entertainment/060.txt
reading file: entertainment/061.txt
reading file: entertainment/

reading file: politics/149.txt
reading file: politics/150.txt
reading file: politics/151.txt
reading file: politics/152.txt
reading file: politics/153.txt
reading file: politics/154.txt
reading file: politics/155.txt
reading file: politics/156.txt
reading file: politics/157.txt
reading file: politics/158.txt
reading file: politics/159.txt
reading file: politics/160.txt
reading file: politics/161.txt
reading file: politics/162.txt
reading file: politics/163.txt
reading file: politics/164.txt
reading file: politics/165.txt
reading file: politics/166.txt
reading file: politics/167.txt
reading file: politics/169.txt
reading file: politics/170.txt
reading file: politics/171.txt
reading file: politics/172.txt
reading file: politics/173.txt
reading file: politics/174.txt
reading file: politics/175.txt
reading file: politics/176.txt
reading file: politics/177.txt
reading file: politics/178.txt
reading file: politics/179.txt
reading file: politics/180.txt
reading file: politics/181.txt
reading 

reading file: sport/203.txt
reading file: sport/204.txt
reading file: sport/205.txt
reading file: sport/206.txt
reading file: sport/207.txt
reading file: sport/208.txt
reading file: sport/209.txt
reading file: sport/211.txt
reading file: sport/212.txt
reading file: sport/213.txt
reading file: sport/214.txt
reading file: sport/215.txt
reading file: sport/216.txt
reading file: sport/217.txt
reading file: sport/218.txt
reading file: sport/219.txt
reading file: sport/220.txt
reading file: sport/221.txt
reading file: sport/222.txt
reading file: sport/223.txt
reading file: sport/224.txt
reading file: sport/225.txt
reading file: sport/226.txt
reading file: sport/227.txt
reading file: sport/228.txt
reading file: sport/229.txt
reading file: sport/230.txt
reading file: sport/232.txt
reading file: sport/233.txt
reading file: sport/234.txt
reading file: sport/235.txt
reading file: sport/236.txt
reading file: sport/237.txt
reading file: sport/238.txt
reading file: sport/239.txt
reading file: sport/

reading file: sport/510.txt
reading file: sport/511.txt
reading file: tech/001.txt
reading file: tech/002.txt
reading file: tech/003.txt
reading file: tech/004.txt
reading file: tech/005.txt
reading file: tech/006.txt
reading file: tech/007.txt
reading file: tech/008.txt
reading file: tech/009.txt
reading file: tech/010.txt
reading file: tech/011.txt
reading file: tech/012.txt
reading file: tech/013.txt
reading file: tech/014.txt
reading file: tech/015.txt
reading file: tech/016.txt
reading file: tech/017.txt
reading file: tech/018.txt
reading file: tech/019.txt
reading file: tech/020.txt
reading file: tech/022.txt
reading file: tech/023.txt
reading file: tech/024.txt
reading file: tech/025.txt
reading file: tech/026.txt
reading file: tech/027.txt
reading file: tech/028.txt
reading file: tech/029.txt
reading file: tech/030.txt
reading file: tech/031.txt
reading file: tech/032.txt
reading file: tech/033.txt
reading file: tech/034.txt
reading file: tech/035.txt
reading file: tech/036.txt

reading file: tech/311.txt
reading file: tech/312.txt
reading file: tech/313.txt
reading file: tech/314.txt
reading file: tech/316.txt
reading file: tech/317.txt
reading file: tech/318.txt
reading file: tech/319.txt
reading file: tech/320.txt
reading file: tech/321.txt
reading file: tech/322.txt
reading file: tech/323.txt
reading file: tech/324.txt
reading file: tech/325.txt
reading file: tech/326.txt
reading file: tech/327.txt
reading file: tech/328.txt
reading file: tech/329.txt
reading file: tech/330.txt
reading file: tech/331.txt
reading file: tech/332.txt
reading file: tech/333.txt
reading file: tech/334.txt
reading file: tech/335.txt
reading file: tech/337.txt
reading file: tech/338.txt
reading file: tech/339.txt
reading file: tech/340.txt
reading file: tech/341.txt
reading file: tech/342.txt
reading file: tech/343.txt
reading file: tech/344.txt
reading file: tech/345.txt
reading file: tech/346.txt
reading file: tech/347.txt
reading file: tech/348.txt
reading file: tech/349.txt
r

In [29]:
data = {'news': x, 'type': y}       
df = pd.DataFrame(data)
print ('writing csv flie ...')
df.to_csv('../dataset.csv', index=False)

writing csv flie ...


In [30]:
def clean_str(string):
    """
    Tokenization/string cleaning for datasets.
    Original taken from https://github.com/yoonkim/CNN_sentence/blob/master/process_data.py
    """
    string = re.sub(r"\'s", "", string)
    string = re.sub(r"\'ve", "", string)
    string = re.sub(r"n\'t", "", string)
    string = re.sub(r"\'re", "", string)
    string = re.sub(r"\'d", "", string)
    string = re.sub(r"\'ll", "", string)
    string = re.sub(r",", "", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", "", string)
    string = re.sub(r"\)", "", string)
    string = re.sub(r"\?", "", string)
    string = re.sub(r"'", "", string)
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"[0-9]\w+|[0-9]","", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()


In [32]:
data = pd.read_csv('../dataset/dataset.csv')
x = data['news'].tolist()
y = data['type'].tolist()

In [33]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /home/soumya/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [34]:
for index,value in enumerate(x):
    print ("processing data:",index)
    x[index] = ' '.join([Word(word).lemmatize() for word in clean_str(value).split()])


processing data: 0
processing data: 1
processing data: 2
processing data: 3
processing data: 4
processing data: 5
processing data: 6
processing data: 7
processing data: 8
processing data: 9
processing data: 10
processing data: 11
processing data: 12
processing data: 13
processing data: 14
processing data: 15
processing data: 16
processing data: 17
processing data: 18
processing data: 19
processing data: 20
processing data: 21
processing data: 22
processing data: 23
processing data: 24
processing data: 25
processing data: 26
processing data: 27
processing data: 28
processing data: 29
processing data: 30
processing data: 31
processing data: 32
processing data: 33
processing data: 34
processing data: 35
processing data: 36
processing data: 37
processing data: 38
processing data: 39
processing data: 40
processing data: 41
processing data: 42
processing data: 43
processing data: 44
processing data: 45
processing data: 46
processing data: 47
processing data: 48
processing data: 49
processing

processing data: 652
processing data: 653
processing data: 654
processing data: 655
processing data: 656
processing data: 657
processing data: 658
processing data: 659
processing data: 660
processing data: 661
processing data: 662
processing data: 663
processing data: 664
processing data: 665
processing data: 666
processing data: 667
processing data: 668
processing data: 669
processing data: 670
processing data: 671
processing data: 672
processing data: 673
processing data: 674
processing data: 675
processing data: 676
processing data: 677
processing data: 678
processing data: 679
processing data: 680
processing data: 681
processing data: 682
processing data: 683
processing data: 684
processing data: 685
processing data: 686
processing data: 687
processing data: 688
processing data: 689
processing data: 690
processing data: 691
processing data: 692
processing data: 693
processing data: 694
processing data: 695
processing data: 696
processing data: 697
processing data: 698
processing da

processing data: 1156
processing data: 1157
processing data: 1158
processing data: 1159
processing data: 1160
processing data: 1161
processing data: 1162
processing data: 1163
processing data: 1164
processing data: 1165
processing data: 1166
processing data: 1167
processing data: 1168
processing data: 1169
processing data: 1170
processing data: 1171
processing data: 1172
processing data: 1173
processing data: 1174
processing data: 1175
processing data: 1176
processing data: 1177
processing data: 1178
processing data: 1179
processing data: 1180
processing data: 1181
processing data: 1182
processing data: 1183
processing data: 1184
processing data: 1185
processing data: 1186
processing data: 1187
processing data: 1188
processing data: 1189
processing data: 1190
processing data: 1191
processing data: 1192
processing data: 1193
processing data: 1194
processing data: 1195
processing data: 1196
processing data: 1197
processing data: 1198
processing data: 1199
processing data: 1200
processing

processing data: 1579
processing data: 1580
processing data: 1581
processing data: 1582
processing data: 1583
processing data: 1584
processing data: 1585
processing data: 1586
processing data: 1587
processing data: 1588
processing data: 1589
processing data: 1590
processing data: 1591
processing data: 1592
processing data: 1593
processing data: 1594
processing data: 1595
processing data: 1596
processing data: 1597
processing data: 1598
processing data: 1599
processing data: 1600
processing data: 1601
processing data: 1602
processing data: 1603
processing data: 1604
processing data: 1605
processing data: 1606
processing data: 1607
processing data: 1608
processing data: 1609
processing data: 1610
processing data: 1611
processing data: 1612
processing data: 1613
processing data: 1614
processing data: 1615
processing data: 1616
processing data: 1617
processing data: 1618
processing data: 1619
processing data: 1620
processing data: 1621
processing data: 1622
processing data: 1623
processing

processing data: 2003
processing data: 2004
processing data: 2005
processing data: 2006
processing data: 2007
processing data: 2008
processing data: 2009
processing data: 2010
processing data: 2011
processing data: 2012
processing data: 2013
processing data: 2014
processing data: 2015
processing data: 2016
processing data: 2017
processing data: 2018
processing data: 2019
processing data: 2020
processing data: 2021
processing data: 2022
processing data: 2023
processing data: 2024
processing data: 2025
processing data: 2026
processing data: 2027
processing data: 2028
processing data: 2029
processing data: 2030
processing data: 2031
processing data: 2032
processing data: 2033
processing data: 2034
processing data: 2035
processing data: 2036
processing data: 2037
processing data: 2038
processing data: 2039
processing data: 2040
processing data: 2041
processing data: 2042
processing data: 2043
processing data: 2044
processing data: 2045
processing data: 2046
processing data: 2047
processing

In [35]:
vect = TfidfVectorizer(stop_words='english',min_df=2)
X = vect.fit_transform(x)
Y = np.array(y)
print ("no of features extracted:",X.shape[1])

no of features extracted: 14788


In [36]:
print(X)

  (0, 152)	0.055759195985616905
  (0, 11490)	0.15313960442945423
  (0, 1480)	0.040271593880598505
  (0, 13375)	0.0579993003409625
  (0, 14336)	0.25506859491276157
  (0, 10232)	0.41019456786940134
  (0, 10455)	0.059018053727134194
  (0, 8302)	0.03516410147580959
  (0, 5554)	0.0379109522010205
  (0, 7212)	0.05508107727770068
  (0, 8597)	0.024264960917341268
  (0, 3321)	0.034872216229808815
  (0, 14707)	0.059870545743321325
  (0, 4124)	0.06581731914163302
  (0, 5035)	0.026960660430899175
  (0, 1293)	0.033355841660371484
  (0, 6933)	0.042900751139905866
  (0, 5675)	0.10655082686681765
  (0, 1218)	0.07105018004332005
  (0, 6175)	0.05878070355832607
  (0, 12394)	0.086642189836323
  (0, 6875)	0.15113436289813323
  (0, 2722)	0.045992382118279176
  (0, 6177)	0.07840946222197227
  (0, 229)	0.05611540613753012
  :	:
  (2224, 13806)	0.02328902364582527
  (2224, 4363)	0.02240854959033025
  (2224, 4401)	0.02069580058889524
  (2224, 4442)	0.02328902364582527
  (2224, 13270)	0.043451201709825825
  (22

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

print ("train size:", X_train.shape)
print ("test size:", X_test.shape)

train size: (1780, 14788)
test size: (445, 14788)


In [47]:
model = RandomForestClassifier(n_estimators=300, max_depth=150,n_jobs=1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

c_mat = confusion_matrix(y_test,y_pred)
kappa = cohen_kappa_score(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
print ("Confusion Matrix:\n", c_mat)
print ("\nKappa: ",kappa)
print ("\nAccuracy: ",acc)

Confusion Matrix:
 [[111   0   1   0   3]
 [  0  67   5   0   0]
 [  3   0  72   1   0]
 [  0   0   0 102   0]
 [  3   2   0   0  75]]

Kappa:  0.9489574836867863

Accuracy:  0.9595505617977528


In [48]:
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [53]:
y_pred = svclassifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred)) 
acc=accuracy_score(y_test,y_pred)
print(acc)

[[107   2   1   1   4]
 [  0  67   4   0   1]
 [  2   0  74   0   0]
 [  0   0   0 102   0]
 [  0   1   0   0  79]]
               precision    recall  f1-score   support

     business       0.98      0.93      0.96       115
entertainment       0.96      0.93      0.94        72
     politics       0.94      0.97      0.95        76
        sport       0.99      1.00      1.00       102
         tech       0.94      0.99      0.96        80

  avg / total       0.96      0.96      0.96       445

0.9640449438202248
